theme: jekyll-theme-cayman
permalink: /:categories/:year/:month/:title/
title: My First website with Github
description: This is a personal website, contains university materials, bio and blog
markdown: kramdown
